### ISSUE TITLE
BottomSheetDialogFragment not included in screenshots?

### ISSUE THREAD

**Issue by amanzan** [Shopify/android-testify#243]
**Describe the bug**
Trying to record the baseline screenshots for an app with a BottomSheetDialogFragment opened. The screenshot doesn't include the BottomSheetDialogFragment, only the everything that is behind it

This issue relates to:
- The Kotlin library
- The Gradle plugin

**To Reproduce**
1. App with a BottomSheetDialogFragment, open the dialog
2. Create a test and click on 'Record baseline' on Android Studio
3. Check the taken screenshot and the BottomSheetDialogFragment is not there

**Expected behavior**
The opened BottomSheetDialogFragment should be included in the screenshot

**Screenshots**
App with BottomSheetDialogFragment opened (disregard bottom nav menu):
![Screenshot_1631722353](https://user-images.githubusercontent.com/3911627/133470262-8d4db025-2c03-444d-ba56-6e4ec5ad30dc.png)

Recorded baseline screenshot:
![ModalsTest_fixedSizeScreenshotCheck](https://user-images.githubusercontent.com/3911627/133470843-47f77004-70e2-4519-809b-6230cfb053ef.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 11.5.2

**Target Android Device (please complete the following information):**
 - Device: Pixel 4
-  Physical or Virtual: Android Virtual Device (Emulator)
 - API Level: 29
- Testify Key: 29-1080x2280@440dp-en_US

**Comment by amanzan** [comment]
@DanielJette would it be possible to extend somehow ScreenshotRule, so that there's a new assertSame function which accepts currentBitmap as parameter? This way, I could take a screenshot of the entire screen and pass it

**Comment by DanielJette** [comment]
Hi @amanzan
Unfortunately there's not currently a way to extend the ScreenshotRule in a meaningful way to allow for customization of the currentBitmap.
However, [there are plans](https://github.com/Shopify/android-testify/issues/227) to significantly expand the extensibility and customizability of the screenshot rule.
This is tentatively scheduled to be included in the 1.2.0 release.

I have a work-in-progress branch here https://github.com/Shopify/android-testify/compare/227-extensible that demonstrates one way that Testify can allow for custom capture methods.

**Comment by jennatauro** [comment]
Hi @DanielJette would this issue also be applicable to `DropdownMenu` from jetpack compose? I'm trying to write a screenshot test for the "expanded" (opened) version of the dropdown and the menu doesn't appear in the screenshot:
| expected | actual |
| - | - |
| ![Screenshot_1644879440](https://user-images.githubusercontent.com/4675165/153960715-54efd8aa-c201-4bc1-84a1-3d1c59cd9218.png) | ![DropdownScreenshotTest_expanded](https://user-images.githubusercontent.com/4675165/153960808-d1d75e5e-73c8-4e16-bd70-394dd9bee070.png) |

I wasn't sure if this was due to a timing issue with when the screenshot is taken or if it's because the dropdown is rendered in a different view hierarchy.

**Comment by DanielJette** [comment]
@jennatauro I added a `DropdownMenu` test to the Sample app and I can confirm that I'm seeing the same error as you are.

Here is the Layout Inspector output:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/5921367/154302513-5fa6f4f0-2c2d-40f2-a18d-bdbe048fb9fa.png">

It appears that the Dropdown is rendered in a different layer than the rest of the composition. I suspect this is likely implemented via a new Window by the compose renderer and this Window is not being captured.

You can find my changes to the Sample here https://github.com/Shopify/android-testify/pull/262

As of yet, I don't know how to resolve this issue, but it might be possible to direct Testify to capture the popup Window. Due to the limitations of Testify, it is not likely possible to capture the entire screen without also capturing the System UI. There is an issue requesting full-screen capture [here](https://github.com/Shopify/android-testify/issues/131).

**Comment by amanzan** [comment]
Hi @DanielJette, I see there is a 1.2.0-beta1 version available. Would this be possible to do in that version then? If so, would you mind guiding me how to approach it?

**Comment by DanielJette** [comment]
Moved to https://github.com/ndtp/android-testify/issues/87
