### ISSUE TITLE
ActivityTestRule deprecated

### ISSUE THREAD

**Issue by oradkovsky** [Shopify/android-testify#244]
**Is your feature request related to a problem? Please describe.**
Please share any plans regarding moving away from using https://developer.android.com/reference/androidx/test/rule/ActivityTestRule.html due to deprecation.

This feedback relates to:
- [x] The Kotlin library
- [ ] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [ ] The sample code
- [ ] The documentation

**Describe the solution you'd like**
The plugin heavily relies on https://developer.android.com/reference/androidx/test/rule/ActivityTestRule.html, while latter being deprecated.

**Describe alternatives you've considered**
Using whatever coming instead of https://developer.android.com/reference/androidx/test/rule/ActivityTestRule.html

**Additional context**
NA

**Comment by DanielJette** [comment]
@oradkovsky Thank you for the feedback

My expectation is that we will migrate the existing `ScreenshotRule` to either leverage [`ActivityScenario`](https://developer.android.com/reference/androidx/test/core/app/ActivityScenario) or possibly [`ActivityScenarioRule`](https://developer.android.com/reference/androidx/test/ext/junit/rules/ActivityScenarioRule). I'm not anticipating that `ActivityTestRule` will be removed from the Android SDK for some time, so I expect that there will be time to develop a quality solution for Testify. 

However, this will likely introduce a significant change to the API and "lifecycle" of Testify, so my plan would be to introduce an alternative non-ActivityTestRule-based solution side-by-side with the existing mechanism, to allow users to transition over without making a big, breaking change all at once. We did something like this with the transition from JUnit3 to JUnit4.

As for specific plans, I would hope we could get something added to a 1.2 release, but that really depends on how different/breaking a scenario-based Testify is.

Are there any specific problems or blockers you're running into right now with the current implementation? Maybe there's something quicker we can do to help rather than waiting on this specific fix.

**Comment by oradkovsky** [comment]
All of the statements above fully make sense to me (not that it matters though :) . My problem is that we already have set of UI tests working on top of `ActivityScenario`. So far I do not see easy way of using existing Testify solution for this (by easy - I mean with slight code modifications of Testify).

**Comment by allefsousa** [comment]
@DanielJette  first of all congratulations for the amazing work. Any predictions about the integration with ActivityScenario? that will be fantastic

**Comment by DanielJette** [comment]
Moved to https://github.com/ndtp/android-testify/issues/88
