### ISSUE TITLE
Screens which inflate views at a later time are never captured

### ISSUE THREAD

**Issue by videogreg93** [Shopify/android-testify#245]
**Describe the bug**
Regardless of which capture method I try, I can never actually capture anything on screen which either inflates views after creation or adds views to a recyclerview. Using `Screenshot.capture()` as a fourth capture method would fix this. `Screenshot.capture()` gives you access to a `bitmap` so comparing shouldn't been an issue.

This issue relates to:
- [x] The Kotlin library
- [ ] The Gradle plugin
- [ ] The IntelliJ Platform plugin
- [ ] The sample code
- [ ] The documentation

**To Reproduce**
Try to screenshot any activity with just a recyclerview into which you add views after `onCreate` of the ` Activity`.

**Expected behavior**
Screenshot is correctly taken.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS

**Target Android Device (please complete the following information):**
 - Device: Pixel
-  Physical or Virtual: Android Virtual Device (Emulator)
 - API Level: 28
- Testify Key: [e.g. Output from `./gradlew testifyKey`]

**Additional context**

**Comment by DanielJette** [comment]
@videogreg93 I was thinking about this problem a little more last night and I'm wondering if you might be running in to a GPU-acceleration problem. Testify's default capture method is not capable of capturing SurfaceViews, such as Google MapView or Jetpack Compose elements. Some other graphical elements such as elevation/shadows are also not captured since they're not present in the Bitmap buffer of the Activity, but rather contained in hard-accelerated surfaces. This means that the default Testify capture methods are not able to "see" that content. In order to capture SurfaceView contents, you will need to use an alternative capture methods that is capable of capturing SurfaceViews.

I would recommend you try enabling [`PixelCopyCapture`](https://github.com/Shopify/android-testify/blob/master/Library/src/main/java/com/shopify/testify/TestifyFeatures.kt#L38):

```kotlin
import com.shopify.testify.TestifyFeatures.PixelCopyCapture

@ScreenshotInstrumentation
@Test
fun default() {
    rule
        .withExperimentalFeatureEnabled(PixelCopyCapture)
        .assertSame()
}
```

PixelCopy grabs the content directly from the GPU on your device, so it's quite sensitive to hardware differences. As such, I recommend you also enable a lower exactness threshold for the matching using `setExactness()`.

```kotlin
import com.shopify.testify.TestifyFeatures.PixelCopyCapture

@ScreenshotInstrumentation
@Test
fun default() {
    rule
        .withExperimentalFeatureEnabled(PixelCopyCapture)
        .setExactness(0.9f)
        .assertSame()
}
```

You can find an example of this [here](https://github.com/Shopify/android-testify/blob/master/Library/src/androidTest/java/com/shopify/testify/ExperimentalPixelCopyTest.kt)

It's possible that this capture method will work for your tests.

**Comment by DanielJette** [comment]
Moved to https://github.com/ndtp/android-testify/issues/91
